# Generated by Django 4.2.6 on 2023-10-06 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_customer_store_custo_last_na_2e448d_idx'),
    ]

    operations = [
        migrations.RunSQL("""
            INSERT INTO store_collection (title)
            VALUES ('collection1')
        """, 
        """
            DELETE FROM store_collection
            WHERE title='collection1'
        """
        )
    ]
