version: '3.9'

services:
  web:
    build: .
    command: ./wait-for-it.sh postgresql:5432 -- ./docker-entrypoint.sh
    ports:
      - 8000:8000
    depends_on:
      - redis
      - postgresql
    restart: on-failure
    volumes:
      - .:/app

  postgresql:
    image: postgres:15.0
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_DB=storefront
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=MyPassword
    volumes:
      - postgresqldata:/var/lib/postgresql/data

  redis:
    image: redis:6.2-alpine
    ports:
      - 6379:6379
    restart: always
    volumes:
      - redisdata:/data

  smtp4dev:
    image: rnwood/smtp4dev:v3
    ports:
      - 5000:80
      - 25:25
    restart: always

  celery:
    build: .
    command: celery -A storefront worker --loglevel=info
    depends_on:
      - redis
    volumes:
      - .:/app

  celery-beat:
    build: .
    command: celery -A storefront beat --loglevel=info
    depends_on:
      - redis
    volumes:
      - .:/app

  flower:
    build: .
    command: celery -A storefront flower
    depends_on:
      - web
      - redis
      - celery
    environment:
      - DEBUG=1
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    ports:
      - 5555:5555

  tests:
    build: .
    command: ./wait-for-it.sh postgresql:5432 -- ptw
    depends_on:
      - redis
    tty: true
    volumes:
      - .:/app

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    links:
      - web

volumes:
  postgresqldata:
  redisdata:
